### ISSUE TITLE
typos

### ISSUE THREAD

**Issue by RoyLab** [GPUOpen-Effects/TressFX#15]
TressFX\amd_tressfx\src\TressFXSimulation.cpp
L256, there should be 'which' not 'wich'

**Comment by mrgreywater** [comment]
There are lots of typos in the comments, but they don't really matter. If they bother you that much, you should go over the project, fix them and create a PR.

To name a few others:
"assgin" Ln219 SceneRender.cpp
"corrisponding" Ln321 SceneRender.cpp
"suure" Ln808 SceneRender.cpp
"bufferss" Ln199 TressFXSimulation.cpp
"pixelinked" Ln111 TressFXRenderer.cpp
"exsist" Ln745 TressFXRenderer.cpp
"unecssary" Ln887 TressFXRenderer.cpp
...

**Comment by jstewart-amd** [comment]
I cleaned this up. I'll push the commit in a minute. We do take PRs for typos, though, as @mrgreywater indicated. That class of pull request is a low-risk way to contribute, if you are interested in the future.

**Comment by mrgreywater** [comment]
LengthConstr**ia**ntsWindAndCollision https://github.com/GPUOpen-Effects/TressFX/blob/master/amd_tressfx/src/Shaders/TressFXSimulation.hlsl#L728
