### ISSUE TITLE
causing error while exporting .tfxskin and .tfxbone form maya

### ISSUE THREAD

**Issue by BleedingChips** [GPUOpen-Effects/TressFX#33]
Maya vision 2016
while exporting .tfxskin:
`#NameError : balabala..\TressFX_Exporter.py line 1036: gobal name 'Point' is not define`
while  exporting .tfxbone
`#indexError : balabala..\TressFX_Exporter.py line 728: list index out of range`
how should i do to avoid those error?
my model file:
[6662.zip](https://github.com/GPUOpen-Effects/TressFX/files/1914543/6662.zip)

**Comment by kuyin** [comment]
I met the same error too, please fix it.

**Comment by BleedingChips** [comment]
.tfxskin is no need for 1.4, so just ignore it.
This Plugin require 4 bone (or more?) in your mesh to export .tfxbone.
